/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as MemberRouteImport } from './routes/member'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as StaffGuestsRouteImport } from './routes/staff/guests'
import { Route as StaffFacilitiesRouteImport } from './routes/staff/facilities'
import { Route as StaffEventsRouteImport } from './routes/staff/events'
import { Route as StaffDiningRouteImport } from './routes/staff/dining'
import { Route as StaffBookingsRouteImport } from './routes/staff/bookings'
import { Route as MemberProfileRouteImport } from './routes/member/profile'
import { Route as MemberNoticesRouteImport } from './routes/member/notices'
import { Route as MemberGuestsRouteImport } from './routes/member/guests'
import { Route as MemberEventsRouteImport } from './routes/member/events'
import { Route as MemberFacilitiesIndexRouteImport } from './routes/member/facilities/index'
import { Route as MemberDiningIndexRouteImport } from './routes/member/dining/index'
import { Route as MemberFacilitiesIdRouteImport } from './routes/member/facilities/$id'
import { Route as MemberDiningIdRouteImport } from './routes/member/dining/$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const StaffGuestsRoute = StaffGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFacilitiesRoute = StaffFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEventsRoute = StaffEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDiningRoute = StaffDiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNoticesRoute = MemberNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => MemberRoute,
} as any)
const MemberGuestsRoute = MemberGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => MemberRoute,
} as any)
const MemberEventsRoute = MemberEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MemberRoute,
} as any)
const MemberFacilitiesIndexRoute = MemberFacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDiningIndexRoute = MemberDiningIndexRouteImport.update({
  id: '/dining/',
  path: '/dining/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberFacilitiesIdRoute = MemberFacilitiesIdRouteImport.update({
  id: '/facilities/$id',
  path: '/facilities/$id',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDiningIdRoute = MemberDiningIdRouteImport.update({
  id: '/dining/$id',
  path: '/dining/$id',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/management': typeof ManagementRoute
  '/member': typeof MemberRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/member/events': typeof MemberEventsRoute
  '/member/guests': typeof MemberGuestsRoute
  '/member/notices': typeof MemberNoticesRoute
  '/member/profile': typeof MemberProfileRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dining': typeof StaffDiningRoute
  '/staff/events': typeof StaffEventsRoute
  '/staff/facilities': typeof StaffFacilitiesRoute
  '/staff/guests': typeof StaffGuestsRoute
  '/member/': typeof MemberIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/member/dining/$id': typeof MemberDiningIdRoute
  '/member/facilities/$id': typeof MemberFacilitiesIdRoute
  '/member/dining/': typeof MemberDiningIndexRoute
  '/member/facilities/': typeof MemberFacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/management': typeof ManagementRoute
  '/member/events': typeof MemberEventsRoute
  '/member/guests': typeof MemberGuestsRoute
  '/member/notices': typeof MemberNoticesRoute
  '/member/profile': typeof MemberProfileRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dining': typeof StaffDiningRoute
  '/staff/events': typeof StaffEventsRoute
  '/staff/facilities': typeof StaffFacilitiesRoute
  '/staff/guests': typeof StaffGuestsRoute
  '/member': typeof MemberIndexRoute
  '/staff': typeof StaffIndexRoute
  '/member/dining/$id': typeof MemberDiningIdRoute
  '/member/facilities/$id': typeof MemberFacilitiesIdRoute
  '/member/dining': typeof MemberDiningIndexRoute
  '/member/facilities': typeof MemberFacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/management': typeof ManagementRoute
  '/member': typeof MemberRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/member/events': typeof MemberEventsRoute
  '/member/guests': typeof MemberGuestsRoute
  '/member/notices': typeof MemberNoticesRoute
  '/member/profile': typeof MemberProfileRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/dining': typeof StaffDiningRoute
  '/staff/events': typeof StaffEventsRoute
  '/staff/facilities': typeof StaffFacilitiesRoute
  '/staff/guests': typeof StaffGuestsRoute
  '/member/': typeof MemberIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/member/dining/$id': typeof MemberDiningIdRoute
  '/member/facilities/$id': typeof MemberFacilitiesIdRoute
  '/member/dining/': typeof MemberDiningIndexRoute
  '/member/facilities/': typeof MemberFacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/management'
    | '/member'
    | '/staff'
    | '/member/events'
    | '/member/guests'
    | '/member/notices'
    | '/member/profile'
    | '/staff/bookings'
    | '/staff/dining'
    | '/staff/events'
    | '/staff/facilities'
    | '/staff/guests'
    | '/member/'
    | '/staff/'
    | '/member/dining/$id'
    | '/member/facilities/$id'
    | '/member/dining/'
    | '/member/facilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/management'
    | '/member/events'
    | '/member/guests'
    | '/member/notices'
    | '/member/profile'
    | '/staff/bookings'
    | '/staff/dining'
    | '/staff/events'
    | '/staff/facilities'
    | '/staff/guests'
    | '/member'
    | '/staff'
    | '/member/dining/$id'
    | '/member/facilities/$id'
    | '/member/dining'
    | '/member/facilities'
  id:
    | '__root__'
    | '/'
    | '/management'
    | '/member'
    | '/staff'
    | '/member/events'
    | '/member/guests'
    | '/member/notices'
    | '/member/profile'
    | '/staff/bookings'
    | '/staff/dining'
    | '/staff/events'
    | '/staff/facilities'
    | '/staff/guests'
    | '/member/'
    | '/staff/'
    | '/member/dining/$id'
    | '/member/facilities/$id'
    | '/member/dining/'
    | '/member/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagementRoute: typeof ManagementRoute
  MemberRoute: typeof MemberRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/staff/guests': {
      id: '/staff/guests'
      path: '/guests'
      fullPath: '/staff/guests'
      preLoaderRoute: typeof StaffGuestsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/facilities': {
      id: '/staff/facilities'
      path: '/facilities'
      fullPath: '/staff/facilities'
      preLoaderRoute: typeof StaffFacilitiesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/events': {
      id: '/staff/events'
      path: '/events'
      fullPath: '/staff/events'
      preLoaderRoute: typeof StaffEventsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dining': {
      id: '/staff/dining'
      path: '/dining'
      fullPath: '/staff/dining'
      preLoaderRoute: typeof StaffDiningRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/notices': {
      id: '/member/notices'
      path: '/notices'
      fullPath: '/member/notices'
      preLoaderRoute: typeof MemberNoticesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/guests': {
      id: '/member/guests'
      path: '/guests'
      fullPath: '/member/guests'
      preLoaderRoute: typeof MemberGuestsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/events': {
      id: '/member/events'
      path: '/events'
      fullPath: '/member/events'
      preLoaderRoute: typeof MemberEventsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/facilities/': {
      id: '/member/facilities/'
      path: '/facilities'
      fullPath: '/member/facilities/'
      preLoaderRoute: typeof MemberFacilitiesIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/dining/': {
      id: '/member/dining/'
      path: '/dining'
      fullPath: '/member/dining/'
      preLoaderRoute: typeof MemberDiningIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/facilities/$id': {
      id: '/member/facilities/$id'
      path: '/facilities/$id'
      fullPath: '/member/facilities/$id'
      preLoaderRoute: typeof MemberFacilitiesIdRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/dining/$id': {
      id: '/member/dining/$id'
      path: '/dining/$id'
      fullPath: '/member/dining/$id'
      preLoaderRoute: typeof MemberDiningIdRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberRouteChildren {
  MemberEventsRoute: typeof MemberEventsRoute
  MemberGuestsRoute: typeof MemberGuestsRoute
  MemberNoticesRoute: typeof MemberNoticesRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberIndexRoute: typeof MemberIndexRoute
  MemberDiningIdRoute: typeof MemberDiningIdRoute
  MemberFacilitiesIdRoute: typeof MemberFacilitiesIdRoute
  MemberDiningIndexRoute: typeof MemberDiningIndexRoute
  MemberFacilitiesIndexRoute: typeof MemberFacilitiesIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberEventsRoute: MemberEventsRoute,
  MemberGuestsRoute: MemberGuestsRoute,
  MemberNoticesRoute: MemberNoticesRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberIndexRoute: MemberIndexRoute,
  MemberDiningIdRoute: MemberDiningIdRoute,
  MemberFacilitiesIdRoute: MemberFacilitiesIdRoute,
  MemberDiningIndexRoute: MemberDiningIndexRoute,
  MemberFacilitiesIndexRoute: MemberFacilitiesIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface StaffRouteChildren {
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffDiningRoute: typeof StaffDiningRoute
  StaffEventsRoute: typeof StaffEventsRoute
  StaffFacilitiesRoute: typeof StaffFacilitiesRoute
  StaffGuestsRoute: typeof StaffGuestsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBookingsRoute: StaffBookingsRoute,
  StaffDiningRoute: StaffDiningRoute,
  StaffEventsRoute: StaffEventsRoute,
  StaffFacilitiesRoute: StaffFacilitiesRoute,
  StaffGuestsRoute: StaffGuestsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagementRoute: ManagementRoute,
  MemberRoute: MemberRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
